/* 레벨 인코딩  */
data work.hsb_mar_encoding;
	set hsb_mar;
	if not missing(female) then do;
		if female = "female" then num_female=1;
		else num_female=0;
	end;
	if not missing(prog) then do;
		if prog = "general" then num_prog=1;
		else if prog = "academic" then num_prog=2;
		else num_prog=3;
	end;
	if not missing(race) then do;
		if race = "hispanic" then num_race=1;
		else if race = "asian" then num_race=2;
		else if race = "african-amer" then num_race=3;
		else num_race=4;
	end;
	if not missing(schtyp) then do;
		if schtyp = "public" then num_schtyp=1;
		else num_schtyp=2;
	end;
	if not missing(ses) then do;
		if ses = "low" then num_ses=1;
		else if ses = "middle" then num_ses=2;
		else num_ses=3;
	end;
run;